### ISSUE TITLE
repl 1.6.0.0 ReflectionTypeLoadException

### ISSUE THREAD

**Issue by InfectedBytes** [xanathar/moonsharp#148]
The repl MoonSharp.exe throws the following exception on startup:
```
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  at System.Reflection.Module._GetTypesInternal(StackCrawlMark& stackMark)
  at System.Reflection.Assembly.GetTypes()
  at MoonSharp.Commands.CommandManager.Initialize() in G:\my\moonsharp\src\MoonSharp\Commands\CommandManager.cs:Line 14.
  at MoonSharp.Program.Main(String[] args) in G:\my\moonsharp\src\MoonSharp\Program.cs:Line 25.
```

**Comment by xanathar** [comment]
Fixed in 1.7
