### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by wledfor2** [xanathar/moonsharp#218]
I was writing a wrapper around NUnit's assert functions, I encountered a strange issue. When running the following code:

```
using System;
using MoonSharp.Interpreter;
using NUnit.Framework;

namespace Test {

	class Test {

		public class TestClass {
			
			//simple wrapper around NUnit.Framework.Assert.Catch
			public DynValue Catch(DynValue testDelegate, DynValue message) {
				Exception e = Assert.Catch(() => testDelegate.Function.Call(), message.CastToString());
				return DynValue.NewTuple(DynValue.NewString(e.GetType().Name), DynValue.NewString(e.Message));

			}

			public DynValue Test() => DynValue.NewTuple(DynValue.NewString("1"), DynValue.NewString("2"));

		}

		public static void Main(string[] args) {

			try {

				UserData.RegisterType<TestClass>();
				Script s = new Script();
				s.Globals["Assert"] = UserData.Create(new TestClass());
				s.DoString(@"
					local a, b = Assert:Catch(function()
						Assert:Catch(function()
						end)
					end)
				");

			} catch (InterpreterException e) {

				Console.WriteLine(e.DecoratedMessage);

			}
		}

	}

}

```

The following exception is produced:
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MoonSharp.Interpreter.Execution.VM.Processor.AssignLocal(SymbolRef symref, DynValue value) in src\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 358
   at MoonSharp.Interpreter.Execution.VM.Processor.ExecStoreLcl(Instruction i) in src\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 370
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in src\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 210
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) in src\MoonSharp.Interpreter\Execution\VM\Processor\Processor.cs:line 67
   at MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args) in src\MoonSharp.Interpreter\Script.cs:line 483
   at MoonSharp.Interpreter.Script.Call(DynValue function) in src\MoonSharp.Interpreter\Script.cs:line 442
   at MoonSharp.Interpreter.Script.DoString(String code, Table globalContext, String codeFriendlyName) in src\MoonSharp.Interpreter\Script.cs:line 331
   at Test.Test.Main(String[] args) in Program.cs:line 29
```

When changing the Lua code to this, it works as expected:
```
Assert:Catch(function()
	Assert:Catch(function()
	end)
end)
```

**Comment by wledfor2** [comment]
It seems that Assert.Catch is actually causing a problem somehow. After replacing Catch with code that does the same thing, it works as expected:

```
			//simple wrapper around NUnit.Framework.Assert.Catch
			public DynValue Catch(DynValue testDelegate, DynValue message) {

				//Exception e = Assert.Catch(() => testDelegate.Function.Call(), message.CastToString());
				Exception e = null;

				try {

					testDelegate.Function.Call();

				} catch(Exception ex) {

					e = ex;

				}

				if (e == null) {

					throw new AssertionException("No exception was thrown");

				}

				return DynValue.NewTuple(DynValue.NewString(e.GetType().Name), DynValue.NewString(e.Message));

			}
```

Weird, but I'll leave the issue open anyway because I think something is still going wrong in the interpreter.

**Comment by wledfor2** [comment]
Oddly enough the issue is caused by NUnit. This works:

```
//simple wrapper around NUnit.Framework.Assert.Catch
public DynValue Catch(DynValue testDelegate, DynValue message) {

	Exception e = null;

	try {

		testDelegate.Function.Call();

	} catch(Exception ex) {

		e = ex;

	}

	if (e == null) {

		throw new ScriptRuntimeException(message.CastToString());

	}

	return DynValue.NewTuple(DynValue.NewString(e.GetType().Name), DynValue.NewString(e.Message));

}
```

This does not:

```
//simple wrapper around NUnit.Framework.Assert.Catch
public DynValue Catch(DynValue testDelegate, DynValue message) {

	Exception e = null;

	try {

		testDelegate.Function.Call();

	} catch(Exception ex) {

		e = ex;

	}

	if (e == null) {

		throw new AssertionException(message.CastToString());

	}

	return DynValue.NewTuple(DynValue.NewString(e.GetType().Name), DynValue.NewString(e.Message));

}
```

Strange, I'll leave the issue open anyway in case anyone can figure out a workaround.
